### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by eltang**
See if you like these changes. Once again, please test if the code still compiles with them as I have not.

### CODE REVIEW

**Comment by vifon** [comment]
```
../../tmk_core/common/action.c: In function ‘process_action’:
../../tmk_core/common/action.c:88:47: error: ‘key’ undeclared (first use in this function)
     action_t action = layer_switch_get_action(key);
```

**Comment by eltang** [comment]
Oops, that should fix it.

**Comment by vifon** [comment]
Now `master` builds. I'll check later if it still works with the cache enabled.

**Comment by vifon** [comment]
Are you sure you want to undefine `layer_switch_get_action` when `PREVENT_STUCK_MODIFIERS` is set? Because that's what is happening right now. I needed to apply the following patch to get it working with the feature enabled, though I'm not sure if that's the best approach. In my opinion `layer_switch_get_action` should be always defined.

``` diff
diff --git a/tmk_core/common/action.c b/tmk_core/common/action.c
index 6c1e955..11140cf 100644
--- a/tmk_core/common/action.c
+++ b/tmk_core/common/action.c
@@ -543,7 +543,11 @@ void clear_keyboard_but_mods(void)

 bool is_tap_key(keypos_t key)
 {
+#if !defined(NO_ACTION_LAYER) && defined(PREVENT_STUCK_MODIFIERS)
+    action_t action = action_for_key(find_source_layer(key), key);
+#else
     action_t action = layer_switch_get_action(key);
+#endif

     switch (action.kind.id) {
         case ACT_LMODS_TAP:
```

**Comment by vifon** [comment]
By the way, I'm becoming genuinely confused by the API changes being introduced. Can you rebase these commits later so I can review them individually with some more meaningful commit messages?

**Comment by eltang** [comment]
Do you fully understand what's going on in `action_tapping.c`? I see that `process_action` and `layer_switch_get_action` are called a lot in it and I'm not sure whether they should or should not use the cache.

**Comment by vifon** [comment]
It's the first time I opened this file so not really, sorry.

**Comment by eltang** [comment]
Well, I suspect that it doesn't matter because most users will not be switching layers between taps (hopefully). What do you not understand about the changes?

**Comment by eltang** [comment]
How about this: Let's put this PR on hold for now and revisit it when I fully understand `action_tapping.c`. I just realized that I had been misreading a small but important part of the code.

**Comment by vifon** [comment]
Mostly what is the real base version you're modifying and I should diff against. Things got pretty messy. That's why I'm asking you to rebase to the current upstream master.

No need to close it. Just modify it later. There is no rush.

**Comment by eltang** [comment]
I'm not quite sure how do that on GitHub. Does the diff in the "Files changed" tab not work for you?

**Comment by vifon** [comment]
Why do you want to do it using the Github WebUI? You probably can't. Use regular Git.

**Comment by eltang** [comment]
I have to close this pull request for reasons unrelated to its content. I will open another one later.

**Comment by eltang** [comment]
I m trying to figure out how git works and I accidentally deleted a file while resolving a merge conflict. How do I get it back?

**Comment by eltang** [comment]
I've tentatively concluded that `layer_switch_get_action` is not necessary. One pull request coming your way! You can update your `modifier-release-fix` branch in the meantime.

**Comment by eltang** [comment]
Could you update the branch to which you want me to send the PR? When I try to create it, it shows a lot of commits through which you can simply fast-forward.

**Comment by vifon** [comment]
Done, I've updated `master`.

**Pull request closed without merging**
